name: Obole
main: me.monnierant.obole.Obole
version: 1.7
description: Gestion d'un system de don.
author: Monnier Antoine
commands:
  obole:
    description: Obole plugin.
    usage: /obole
  ob:
    description: Obole plugin.
    usage: /ob
permissions:
  obole.get:
    description: Ability to get cadeaux.
  obole.get.accept:
    description: Ability to realy get cadeaux.
  obole.check:
    description: Ability to check on donations and view their information.
  obole.setwall:
    description: Ability to set the sign wall that new donator's names are added to.
  obole.reload:
    description: Ability to reload the plugin configuration.
  obole.recent:
    description: Ability to view a listing of recent donations.